### ISSUE TITLE
Automatic version updates for github actions with dependabot

### ISSUE THREAD

**Issue by iemejia** [apache/arrow-ballista#127]
Dependabot supports automatic version updates for github actions. arrow-ballista can benefit of this to keep up with github-actions improvements.

**Comment by liukun4515** [comment]
> Dependabot supports automatic version updates for github actions. arrow-rs can benefit of this to keep up with github-actions improvements.

could you please give the commit of the arrow-rs? I can't find it.
@iemejia

**Comment by iemejia** [comment]
I mean that arrow-ballista. I mentioned arrow-rs because I did the same type of PR for arrow-rs but i meant arrow-ballista
