### ISSUE TITLE
Implement Python bindings for BallistaContext

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-ballista#15]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
We have Python bindings for DataFusion's ExecutionContext. It would be good to also support Ballista's BallistaContext so that we can use Python to run distributed queries.

**Describe the solution you'd like**
Probably something like this?

```python
import ballista

ctx = ballista.BallistaContext
df = ctx.read_parquet(...)
```

**Describe alternatives you've considered**
Another approach might be to have ballista be an optional feature of DataFusion and then enable new methods on the DataFusion ExecutionContext instead but that would probably result in tons of additional dependencies and blur the lines between DataFusion and Ballista and I think there is a strong case for DataFusion=lib/embedded and Ballista=distributed.

**Additional context**
N/A

**Comment by nl5887** [comment]
Related to #58

**Comment by andygrove** [comment]
This has now been implemented.
