### ISSUE TITLE
Executor should use all available cores by default

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-ballista#218]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Ballista default performance is poor because we default to 4 concurrent tasks. This can give a bad impression to someone comparing to other engines like Spark that use all available cores by default.

**Describe the solution you'd like**
I would like to default to all available cores instead. This would match the behavior in Spark.

**Describe alternatives you've considered**

**Additional context**

**Comment by yahoNanJing** [comment]
Agree.
