### ISSUE TITLE
CLI uses DataFusion context if no host or port are provided

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-ballista#219]
**Describe the bug**
The Ballista CLI executes queries against a DataFusion context, not Ballista, if no host and port are provided.

**To Reproduce**
:point_up: 

**Expected behavior**
We should either remove this option or make it use Ballista in local mode.

**Additional context**
None

**Comment by r4ntix** [comment]
If the host and port parameter is not provided, do we use `BallistaContext::standalone` mode?

**Comment by andygrove** [comment]
> If the host and port parameter is not provided, do we use `BallistaContext::standalone` mode?

Yes, exactly.

**Comment by r4ntix** [comment]
> > If the host and port parameter is not provided, do we use `BallistaContext::standalone` mode?
> 
> Yes, exactly.

Ok, I will learn the CLI code and try to submit a PR for this :)
