### ISSUE TITLE
`dev/release/README.md` is outdated

### ISSUE THREAD

**Issue by iajoiner** [apache/arrow-ballista#228]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)
The `dev/release/README.md` is already outdated since Ballista is its own repo now and that DataFusion has 2 releases per month.
**Describe the solution you'd like**
Edit `dev/release/README.md` so that it is more up to date.
**Describe alternatives you've considered**

**Additional context**
We can make the changes while releasing Ballista 0.8.0 which I can help with.

**Comment by andygrove** [comment]
Hi @iajoiner  - please see https://github.com/apache/arrow-ballista/pull/183
