### ISSUE TITLE
Add user guide section on Flight SQL support

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-ballista#230]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
We have no docs on Flight SQL support AFAIK

**Describe the solution you'd like**
Add user guide section on Flight SQL support

**Describe alternatives you've considered**

**Additional context**

**Comment by avantgardnerio** [comment]
Thanks, S&T can take this.

**Comment by avantgardnerio** [comment]
This is basically done, but is now dependent on the docker PR getting merged to use the simplified instructions.
