### ISSUE TITLE
Cannot build Docker images on macOS 12.5.1 with M1 chip

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-ballista#234]
**Describe the bug**

```
#6 3.081 cc1: error: unrecognized command line option '-m64'
#6 3.083 make[1]: *** [Makefile:678: apps/app_rand.o] Error 1
#6 3.083 make[1]: Leaving directory '/tmp/openssl-1.1.1b'
```
**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by rahulpenti** [comment]
Docker on M1 leverages aarch64 which is causing the failure. The docker build code currently is based on x86_64 architecture. Support for x86_64 in Mac is provided using Rosetta. We can force docker to use it https://github.com/rahulpenti/arrow-ballista/pull/1 

If we use Rosetta, the emulation is increasing the integration tests duration considerably. I think it is beneficial to add support for aarch64. https://github.com/rahulpenti/arrow-ballista/pull/2  (* This is my first contribution. Please do let me know if there is a discussion forum to propose such changes)

**Comment by rahulpenti** [comment]
This is resolved with the recent change of installing openssl instead of building it from source. It handles the above architecture discrepancy

**Comment by andygrove** [comment]
I confirmed that I can now build docker images and run docker compose on Mac M1. Thanks @rahulpenti and @avantgardnerio
