### ISSUE TITLE
Initial query stages read parquet files and repartition them needlessly

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-ballista#243]
**Describe the bug**

![shuffle-parquet](https://user-images.githubusercontent.com/934084/190934989-e0e876c7-83ab-4ca5-a290-a4337e91f9ac.png)

**To Reproduce**

**Expected behavior**
We should not shuffle the input files like this

**Additional context**

**Comment by andygrove** [comment]
@yahoNanJing @thinkharderdev I found this during testing today with https://github.com/apache/arrow-ballista/pull/242

**Comment by andygrove** [comment]
I may have been premature in creating this issue. This stage is an input to a join. I will think about this some more.

![join](https://user-images.githubusercontent.com/934084/190936713-32bca882-4671-4801-b0fc-bb158f1f357b.png)

**Comment by yahoNanJing** [comment]
Hi @andygrove, I don't think it's an issue. For a hash join, we need to do repartition each tables.
