### ISSUE TITLE
[UI] Add ability to render query plans

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-ballista#275]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
I can currently download query plans in dot format from the scheduler REST API and then use graphviz to transform them into images. I would like to be able to view them directly in the UI as well.

**Describe the solution you'd like**
Perhaps https://github.com/magjac/d3-graphviz will help

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by onthebridgetonowhere** [comment]
I'd love to have a go at this. It seems rather straightforward (though I am not too familiar with Typescript). Would the image open in a new page, in a modal box, or it would be like hide/show below the query status?
