### ISSUE TITLE
SQL with order by limit returns nothing

### ISSUE THREAD

**Issue by yahoNanJing** [apache/arrow-ballista#334]
**Describe the bug**

A SQL with order by limit returns nothing. It seems it's caused by https://github.com/apache/arrow-datafusion/pull/3545

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by Ted-Jiang** [comment]
will fix this.

**Comment by mingmwang** [comment]
is it still an issue after upgrading to latest DataFusion ?

**Comment by Ted-Jiang** [comment]
Fixed by updated df version.
