### ISSUE TITLE
Use local shuffle reader in containerized environments

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-ballista#356]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
https://github.com/apache/arrow-ballista/pull/347 adds a local shuffle reader. It uses the shuffle read URL to determine if a fetch is local or not. This works well when running as standalone processes but does not work so well in a containerized environment such as k8s where multiple executors could be running on the same host but in different containers.

**Describe the solution you'd like**
Why don't we just look on disk to see if the shuffle files exist locally

**Describe alternatives you've considered**
None

**Additional context**
See discussion at https://github.com/apache/arrow-ballista/pull/347#discussion_r995794572

**Comment by andygrove** [comment]
@Ted-Jiang What do you think of this idea?

**Comment by Ted-Jiang** [comment]
Sounds like a better approach! 👍 I will make another PR.
