### ISSUE TITLE
Ballista 0.10.0 Release (Nov 2022)

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-ballista#361]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I plan on cutting the release candidate on November 18th. It would be nice to get as many of these features in as possible, but none should block the release.

- [ ] Features & Bug Fixes
  - [ ] See https://github.com/apache/arrow-ballista/milestone/1
- [ ] Release Process
  - [ ] Prepare the release candidate
  - [ ] Publish the release once the vote passes
  - [ ] Blog post

**Describe the solution you'd like**
:point_up: 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by andygrove** [comment]
@thinkharderdev @yahoNanJing I am now planning on releasing 0.10.0 early (in the next few days) to unblock master for new PRs. Let me know if any objection.

**Comment by thinkharderdev** [comment]
> @thinkharderdev @yahoNanJing I am now planning on releasing 0.10.0 early (in the next few days) to unblock master for new PRs. Let me know if any objection.

Nope, sounds good to me!
