### ISSUE TITLE
Incorrect documentation for building Ballista on Linux when using docker-compose

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-ballista#362]
**Describe the bug**
The following pages have incorrect instructions for building and running with docker-compose:

The page at https://github.com/apache/arrow-ballista/blob/master/benchmarks/README.md has:

```
cargo build --release
docker-compose up --build
```

The page at https://github.com/apache/arrow-ballista/blob/master/docs/source/user-guide/flightsql.md has these specific instructions for Linux:

```
cargo build --release --all --features flight-sql
docker-compose up --build
```

Using the latter as an example, docker-compose fails to start the scheduler:

```
Step 9/14 : COPY ballista/ui/scheduler/build /var/www/html
COPY failed: file not found in build context or excluded by .dockerignore: stat ballista/ui/scheduler/build: file does not exist
```

**To Reproduce**
Clone the repo into a new directory and follow the instructions above

**Expected behavior**

**Additional context**

**Comment by avantgardnerio** [comment]
@andygrove @ianmcook we need to get this merged into apache's CI & the docs: https://github.com/spaceandtimelabs/arrow-ballista/blob/master/.circleci/config.yml#L51

**Comment by andygrove** [comment]
I think you meant to ping @iajoiner
