### ISSUE TITLE
Support for multi-scheduler deployments

### ISSUE THREAD

**Issue by thinkharderdev** [apache/arrow-ballista#39]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

The current architecture only support single scheduler deployments. This has two problems I believe:

1. It is not ideal for low-latency interactive queries as the scheduler can potentially take a significant time to restart in the case of failure (especially if the serialized state is large). 
2. Query planning itself is not always a trivial mount of work. For instance, when planning a `ParquetExec`, the scheduler may need to read metadata from a large number of parquet files to gather statistics.  

**Describe the solution you'd like**

I would like to see Ballista support multiple schedulers. Essentially I would like to put N schedulers beings a load balancer and have both external clients and the executors send requests to the load balancer. 

The current implementation is not designed for this as the scheduler state is essentially maintained in memory and only flushed to the state backend for the purposes of recovering from a scheduler restart. 

I would propose the following high-level changes:
1. Client-side caching, if required, should be encapsulated in the `StateBackendClient` so it can be a backend-specific concern. 
2. We should support `redis` as a state backend so we can hopefully avoid the need for client-side cacheing entirely. 
3. I think we can avoid the need for distributed locking by refactoring the backend state data structures to avoid the need for locking in the first place. This should mostly be a matter of tracking executor resources and stage task completions with atomic counters.  

**Describe alternatives you've considered**

We could support only single-scheduler deployments. Alternatively, we can try to support multi-scheduler deployments with etcd. 

**Additional context**

Ectd/Redis and multi-scheduler deployments are, strictly speaking, completely separate issues but I did want to raise the question of whether etcd is the right default for non-standalone deployments. Likewise, if we do add support for Redis should we maintain support for both etcd and Redis or standardize on one or the other. I think these questions are highly related, but it makes sense to address them separately then I'm fine with that as well.

**Comment by smallzhongfeng** [comment]
So, is there any relevant deployment documentation here? @thinkharderdev  @andygrove
