### ISSUE TITLE
Upgrade to DataFusion 14.0.0

### ISSUE THREAD

**Issue by Dandandan** [apache/arrow-ballista#445]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
To prepare for next version (get new feature / performance improvements )

**Describe the solution you'd like**
Update DataFusion to a recent commit.

**Describe alternatives you've considered**

**Additional context**

**Comment by yahoNanJing** [comment]
Hi @Dandandan, will Datafusion be upgraded to 14.0.0?

**Comment by yahoNanJing** [comment]
Actually, we have just upgrade DataFusion dependency to the latest commit. Maybe I can take on this.
