### ISSUE TITLE
Make the delayed time interval for cleanup job data in both scheduler and executor configurable

### ISSUE THREAD

**Issue by yahoNanJing** [apache/arrow-ballista#469]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Currently it's hard coded by 5 minutes. It's not flexible for different situations and environment. And it's better to distinguish the delayed time interval for shuffle data and job metadata in sled by different values. For example, 
- for the shuffle data, it's OK to delete them in a very short delayed time. 5 minutes is OK.
- for the job metadata in sled, it's better to keep it longer. Maybe hours is better.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mingmwang** [comment]
There are couple of hard coding configurations in Ballista now, it is better we resolve those in a PR.
