### ISSUE TITLE
ballista ui fails to build

### ISSUE THREAD

**Issue by hokiegeek2** [apache/arrow-ballista#594]
**Describe the bug**
Attempted to build the ballista ui via the following command:

```
sh dev/build-ui.sh
```

Resulted in the following error:

![image](https://user-images.githubusercontent.com/10785153/212327729-3fe5c75e-7412-40fb-b32f-06c15c385437.png)

This error makes sense, because the file is not there:

![image](https://user-images.githubusercontent.com/10785153/212328161-ade605e6-2c0a-4485-af1c-97761cc0161c.png)

So how does one build the ballista scheduler ui?

**To Reproduce**

from arrow-ballista root directory, execute the following command:

```
sh dev/build-ui.sh
```

**Comment by avantgardnerio** [comment]
@hokiegeek2 and @andygrove please see https://github.com/apache/arrow-ballista/pull/597 for a fix and explaination.

**Comment by hokiegeek2** [comment]
@avantgardnerio ah, nice! Thanks for pointing this out! Very cool, really appreciate the follow-up!t  Question -> how does one startup the UI? Once I have that info I am totally good-to-go w/ this really cool project.

**Comment by avantgardnerio** [comment]
> @avantgardnerio ah, nice! Thanks for pointing this out! Very cool, really appreciate the follow-up!t Question -> how does one startup the UI? Once I have that info I am totally good-to-go w/ this really cool project.

For react development? That's a good question. I've only worked with deploying the react app. There appears to be documentation on the React development process [here](https://github.com/apache/arrow-ballista/tree/master/ballista/scheduler/ui#run-client-project).

**Comment by hokiegeek2** [comment]
@avantgardnerio no, just be able to deploy and access the UI

**Comment by avantgardnerio** [comment]
oh, I think then just:

```
docker-compose up
```

and visit port `80`.

**Comment by hokiegeek2** [comment]
ah, gotcha, looking at the docker compose files now. I just need to translate to bare metal and kubernetes deployments then

**Comment by andygrove** [comment]
Here is the k8s deployment guide: https://arrow.apache.org/ballista/user-guide/deployment/kubernetes.html

**Comment by hokiegeek2** [comment]
@andygrove cool, yeah, so there's some type of script in the scheduler image that starts up the scheduler ui I guess. I'll check that out when I do the k8s deployment.

**Comment by avantgardnerio** [comment]
> @andygrove cool, yeah, so there's some type of script in the scheduler image that starts up the scheduler ui I guess. I'll check that out when I do the k8s deployment.

here I think: https://github.com/apache/arrow-ballista/blob/85dc0836bf37cac39c5e3f5629550efd0be5b1c0/dev/docker/scheduler-entrypoint.sh#L23

**Comment by hokiegeek2** [comment]
@avantgardnerio cool, that looks correct to me, thank you!

**Comment by hokiegeek2** [comment]
closing this issue per this pending [PR](https://github.com/apache/arrow-ballista/pull/597). Thanks to @avantgardnerio and @andygrove for addressing this issue -> thanks guys! 💯
