### ISSUE TITLE
Python: Remove SessionContext, rename BallistaContext to SessionContext

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-ballista#595]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
The Python bindings contain two contexts and this is confusing for new users, and for me when I forget how everything works after a long break from the project.

We should remove SessionContext (which is the DataFusion context) and rename BallistaContext to SessionContext. This would allow users to switch easily between DataFusion and Ballista just by changing an import.

**Describe the solution you'd like**
As above. Also docs and examples (if we have any) will need updating.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by hokiegeek2** [comment]
@andygrove ah, cool! Yeah, I am a new user and was confused by this yesterday when I tried to run an example

![image](https://user-images.githubusercontent.com/10785153/212368819-a2a1e798-a2cc-418a-9e1d-e38e5a73093a.png)

Was able to figure out the SessionContext is the one we need:

![image](https://user-images.githubusercontent.com/10785153/212369764-e56b0537-f3a0-4695-9d1b-500f8c8e3db5.png)

BTW, this is a great project, very cool stuff! 👍

**Comment by hokiegeek2** [comment]
@andygrove do you have any guidance on #594 ?

**Comment by andygrove** [comment]
There is only one context now, so closing this. Also, the Python bindings are no longer in this repo.
