### ISSUE TITLE
jobs from python client not showing up in Scheduler UI

### ISSUE THREAD

**Issue by hokiegeek2** [apache/arrow-ballista#625]
**Describe the bug**
I am not totally sure this is a bug. The key thing is that I'm concerned that the ballista requests being submitted from my Python shell are not being distributed across my four-node cluster. I see the executors in the ui:

![image](https://user-images.githubusercontent.com/10785153/214130380-66cb5022-6fbb-40d6-8111-0bc134a443c9.png)

the ui is running here:

![image](https://user-images.githubusercontent.com/10785153/214131846-7482e801-2a8a-4e6a-9b65-9c90845fc06b.png)

But I don't see any jobs:

![image](https://user-images.gu

but it appears jobs are running:

![image](https://user-images.githubusercontent.com/10785153/214131660-5df7b390-a964-4931-8311-6c99259ed3b3.png)

I also don't see anything in the logs, so not sure if I am missing a config somewhere?

**Comment by andygrove** [comment]
You need to use BallistaContext rather than SessionContext. See https://github.com/apache/arrow-ballista/issues/595 for more details. Basically you are running thee query in DataFusion in the Python process and not in the Ballista cluster.

**Comment by hokiegeek2** [comment]
@andygrove thanks for the follow-up! On a hunch I did just that yesterday and got things working in terms of the sql API part:

![image](https://user-images.githubusercontent.com/10785153/214246976-6ab28ea7-482a-47bd-bc3e-8f50ba9a166c.png)

so basically with BallistaContext the means to get a BallistaDataFrame is to execute a query against the sql API, works for me.

**Comment by hokiegeek2** [comment]
@andygrove closing this issue, thanks for the clarification (and reminder about #595
