### ISSUE TITLE
Move Python bindings to separate repo?

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-ballista#635]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
I was chatting with @yahoNanJing, and he asked about moving the Python bindings to a separate repo. I support this if that is what the other maintainers want.

## Pros

- Core Ballista can move faster because it will just require Rust knowledge
- Makes it easier for the Python bindings to re-use the datafusion-python crate, which has a different release schedule than DataFusion core

## Cons

- There is a risk that the Python bindings become unmaintained
- This creates additional work for creating releases
- It makes it less likely that Ballista will be a compelling solution for Python users

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by andygrove** [comment]
@avantgardnerio @thinkharderdev @Dandandan WDYT?

**Comment by thinkharderdev** [comment]
> @avantgardnerio @thinkharderdev @Dandandan WDYT?

No objection from me. I don't really use the Python bindings but think it's a useful feature given Python is so common in datas science circles.

**Comment by avantgardnerio** [comment]
I'd prefer that. I have little python knowledge myself, so when it comes to fixing bindings I find myself of little help. Nowadays I tend to prefer repos per language rather than single mono-repos.

However, I understand that shifts the burden onto fewer people to maintain them, so I defer to you on the matter.

**Comment by andygrove** [comment]
I went ahead and created https://github.com/apache/arrow-ballista-python

Any volunteers for moving the code over?

**Comment by iajoiner** [comment]
I will take it.

**Comment by iajoiner** [comment]
https://github.com/apache/arrow-ballista-python/pulls
