### ISSUE TITLE
Rust / Check Cargo.toml formatting (amd64, stable) (pull_request) Failing

### ISSUE THREAD

**Issue by jiangzhx** [apache/arrow-ballista#662]
**Describe the bug**
Rust / Check Cargo.toml formatting (amd64, stable) (pull_request) Failing

**To Reproduce**
submit a pr.

**Comment by thinkharderdev** [comment]
FYI Fixed this in https://github.com/apache/arrow-ballista/pull/658. If that PR cannot be merged shortly (it's rather large) then we can pull into a separate one

**Comment by jiangzhx** [comment]
> FYI Fixed this in #658. If that PR cannot be merged shortly (it's rather large) then we can pull into a separate one

it's my pr https://github.com/apache/arrow-ballista/pull/661 .

still got error on github action https://github.com/apache/arrow-ballista/actions/runs/4140311128/jobs/7159094110#step:8:1

**Comment by thinkharderdev** [comment]
> > FYI Fixed this in #658. If that PR cannot be merged shortly (it's rather large) then we can pull into a separate one
> 
> it's my pr #661 .
> 
> still got error on github action https://github.com/apache/arrow-ballista/actions/runs/4140311128/jobs/7159094110#step:8:1

Right, #658 would have to be merged or you can just cherry-pick the commit with the fix.

**Comment by andygrove** [comment]
Just fyi, DataFusion had the same issue and resolved it: https://github.com/apache/arrow-datafusion/issues/5180

**Comment by jiangzhx** [comment]
thanks everyone,it's fixed!
