### ISSUE TITLE
Building Docker images on main branch fails

### ISSUE THREAD

**Issue by paolorechia** [apache/arrow-ballista#717]
**Describe the bug**
Docker image build fails with the following error:

```
+ cd ballista/scheduler/ui
[2422](https://github.com/paolorechia/arrow-ballista/actions/runs/4517673072/jobs/7957036021#step:3:2423)
+ yarn install
[2423](https://github.com/paolorechia/arrow-ballista/actions/runs/4517673072/jobs/7957036021#step:3:2424)
yarn install v1.22.19
[2424](https://github.com/paolorechia/arrow-ballista/actions/runs/4517673072/jobs/7957036021#step:3:2425)
[1/4] Resolving packages...
[2425](https://github.com/paolorechia/arrow-ballista/actions/runs/4517673072/jobs/7957036021#step:3:2426)
[2/4] Fetching packages...
[2426](https://github.com/paolorechia/arrow-ballista/actions/runs/4517673072/jobs/7957036021#step:3:2427)
error sockjs-client@1.6.1: The engine "node" is incompatible with this module. Expected version ">=12". Got "10.24.0"
[2427](https://github.com/paolorechia/arrow-ballista/actions/runs/4517673072/jobs/7957036021#step:3:2428)
error Found incompatible module.
```

**To Reproduce**
```
git clone git@github.com:apache/arrow-ballista.git
cd arrow-ballista
./dev/build-ballista-docker.sh
```

**Expected behavior**
Ballista docker images are successfully built. 

**Additional context**
It seems like the node version used by the docker image is no longer supported by the ` sockjs-client@1.6.1`. It seems we'd have two options to solve this:

1. Downgrade ` sockjs-client@1.6.1`
2. Upgrade the base node version used in the build.

Perhaps one option going with 2 is to integrate nvm (Node Version Manager: https://github.com/nvm-sh/nvm#install--update-script) into the docker build, so we can easily update the used node version? I might give this a go if I have time.

**Comment by brunocous** [comment]
Building still fails on main (commit 9b4a12191aac37bda6d0c5e933377698687872b9).

> Compiling pest_generator v2.5.6
> error[E0004]: non-exhaustive patterns: `pest_meta::optimizer::OptimizedExpr::NodeTag(_, _)` not covered
>    --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/pest_generator-2.5.6/src/generator.rs:378:11
>     |
> 378 |     match expr {
>     |           ^^^^ pattern `pest_meta::optimizer::OptimizedExpr::NodeTag(_, _)` not covered
>     |
> note: `pest_meta::optimizer::OptimizedExpr` defined here
>    --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/pest_meta-2.6.0/src/optimizer/mod.rs:142:5
>     |
> 114 | pub enum OptimizedExpr {
>     | ----------------------
> ...
> 142 |     NodeTag(Box<OptimizedExpr>, String),
>     |     ^^^^^^^ not covered
>     = note: the matched value is of type `pest_meta::optimizer::OptimizedExpr`
> help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern or an explicit pattern as shown
>     |
> 519 ~         }
> 520 +         pest_meta::optimizer::OptimizedExpr::NodeTag(_, _) => todo!()
>     |
> 
> error[E0004]: non-exhaustive patterns: `pest_meta::optimizer::OptimizedExpr::NodeTag(_, _)` not covered
>    --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/pest_generator-2.5.6/src/generator.rs:524:11
>     |
> 524 |     match expr {
>     |           ^^^^ pattern `pest_meta::optimizer::OptimizedExpr::NodeTag(_, _)` not covered
>     |
> note: `pest_meta::optimizer::OptimizedExpr` defined here
>    --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/pest_meta-2.6.0/src/optimizer/mod.rs:142:5
>     |
> 114 | pub enum OptimizedExpr {
>     | ----------------------
> ...
> 142 |     NodeTag(Box<OptimizedExpr>, String),
>     |     ^^^^^^^ not covered
>     = note: the matched value is of type `pest_meta::optimizer::OptimizedExpr`
> help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern or an explicit pattern as shown
>     |
> 651 ~         }
> 652 +         pest_meta::optimizer::OptimizedExpr::NodeTag(_, _) => todo!()
>     |
> 
> For more information about this error, try `rustc --explain E0004`.
> error: could not compile `pest_generator` due to 2 previous errors
> warning: build failed, waiting for other jobs to finish..

**Comment by dadepo** [comment]
Still got this issue. Running `eba125e1` but the build still fails

> + yarn install
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
error sockjs-client@1.6.1: The engine "node" is incompatible with this module. Expected version ">=12". Got "10.24.0"
error Found incompatible module.

**Comment by avantgardnerio** [comment]
I was unable to reproduce this issue - I was able to follow the reproduction instructions in the PR, and got this:

```
Successfully built d61ae9d0ced5
Successfully tagged apache/arrow-ballista-cli:0.11.0
bgardner@bg-tensorbook:~/workspace/arrow-ballista$ 
```

**Comment by avantgardnerio** [comment]
I also see that the scripts specifically mention 18.X: https://github.com/apache/arrow-ballista/blob/aba150616b210a9164ee8d9527a7e130be90d96b/dev/docker/ballista-builder.Dockerfile#L29
