### ISSUE TITLE
Critical bug for flight sql on version 0.11.0

### ISSUE THREAD

**Issue by nbokarev** [apache/arrow-ballista#756]
**Describe the bug**
While running this query I get the following error
```
create external table trips
stored as parquet
location 'files/fhv_tripdata_2023-01.parquet' ;
```

```
SQL Error: Error while executing SQL "create external table trips
stored as PARQUET
location 'files/fhv_tripdata_2023-01.parquet'": Error building plan: Execution error: Unable to find factory for PARQUET
```

Similar errors occur also with CSV source files:
```
Unable to find factory for CSV
```

Everything works normally with 0.10.0
**To Reproduce**
1. Run local ballista cluster with version 0.11.0
```
ballista-scheduler
ballista-executor
```

2. Connect to it with Arrow Flight SQL JDBC (I use DBeaver)
3. Run query to create table from parquet file, for example:
```
create external table trips
stored as parquet
location '/Users/nikita.bokarev/files/fhv_tripdata_2023-01.parquet' ;
```

**Expected behavior**
I expect this queries to work on 0.11.0 as it works on 0.10.0

**Additional context**
I use Arrow Flight JDBC Driver from here: https://www.dremio.com/drivers/jdbc/

**Comment by r4ntix** [comment]
Thanks report this!

I'm not familiar with the JDBC driver provided by dremio, but it works normally with [flight-sql-jdbc-driver 10.0.1](https://repo1.maven.org/maven2/org/apache/arrow/flight-sql-jdbc-driver/10.0.1/) and DBeaver  23.0.3 in my local env.

**Comment by nbokarev** [comment]
Thanks, it works) I guess, its worth adding your driver links to the docs
