### ISSUE TITLE
[feature] Increase the load balancing strategy of the machine

### ISSUE THREAD

**Issue by smallzhongfeng** [apache/arrow-ballista#832]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Since the current Slots allocation strategy only compares the remaining slots of each executor when sorting, we can add a load balancing comparison method, because the models of each executor are different, and it is possible that machines with better performance can run more task

**Describe the solution you'd like**
I think our better way is to obtain cpu, memory, disk and other statistical information to make a weighted average, and then get a score, based on this score to determine the priority of assigning tasks to a certain executor

**Comment by smallzhongfeng** [comment]
cc plz~ @thinkharderdev @avantgardnerio

**Comment by yahoNanJing** [comment]
How about using different task slots for different executors?

**Comment by smallzhongfeng** [comment]
Sorry.... I can't get your point. Could you be more specific about this strategy?

**Comment by thinkharderdev** [comment]
> Sorry.... I can't get your point. Could you be more specific about this strategy?

I believe he means that the number of task slots is configured on a per-executor basis. When the executor registers with the scheduler it informs the scheduler how many available task slots it has and the scheduler tracks task slots at the executor level so there is no need for all executors to have the same number of slots. If you have executors which can handle more concurrency then you can just configure those executors to register with more task slots.

**Comment by smallzhongfeng** [comment]
Thanks for your reply! I got it, but let me give an extreme example, if executor1 has one core and is configured with 10 slots, and another executor2 has 10 cores and is configured with 2 slots, will executor1 be given priority to allocate 10 slots, but according to In terms of machine performance, executor2 should be assigned with higher priority, right? @thinkharderdev @yahoNanJing

**Comment by Dandandan** [comment]
@smallzhongfeng 

So the general idea is to allocate slots in accordance to the number of cores:

executor1 has 1 core -> configure this executor with 1 slot
executor2 has 10 cores -> configure this executor with 10 slots

**Comment by Dandandan** [comment]
The executors themselves report back on completed tasks, so if a slot is free it will be filled whenever a new task is available.

**Comment by smallzhongfeng** [comment]
> @smallzhongfeng
> 
> So the general idea is to allocate slots in accordance to the number of cores:
> 
> executor1 has 1 core -> configure this executor with 1 slot executor2 has 10 cores -> configure this executor with 10 slots

Yes, if I have read the code, I will configure it like this, but for users, if they don’t care about the configuration, I think we can have an adaptive ability, for example, we can automatically obtain the number of cores of the current machine, and then set A ratio is obtained by dividing the configured slot and the number of cores, and the priority task with a higher ratio is assigned to this batch of executors for execution.

**Comment by smallzhongfeng** [comment]
If we have many machines, but different models, it is impossible for us to manually modify the configuration.

**Comment by thinkharderdev** [comment]
> If we have many machines, but different models, it is impossible for us to manually modify the configuration.

The executor will by default use the number of available cores for it's concurrent task slot configuration, so you shouldn't need to do any special configuration if you're okay with that default.

**Comment by smallzhongfeng** [comment]
https://github.com/apache/arrow-ballista/issues/832#issuecomment-1615839482

What do you think of this proposal? @thinkharderdev

**Comment by thinkharderdev** [comment]
> [#832 (comment)](https://github.com/apache/arrow-ballista/issues/832#issuecomment-1615839482)
> 
> What do you think of this proposal? @thinkharderdev

Seems reasonable

**Comment by smallzhongfeng** [comment]
Could I raise a pr about it ? :-)

**Comment by yahoNanJing** [comment]
> If we have many machines, but different models, it is impossible for us to manually modify the configuration.

This part can be done at the executor start up script. In the script we can get the node cpu core if you want and then set the config. As for me, the cpu core number is a redundant part for the resource. And what's more, in some case, multiple executors may reside on one machine. Then it's not good to depend the node cpu core number for task assignment.

**Comment by smallzhongfeng** [comment]
> This part can be done at the executor start up script

Good idea!

> As for me, the cpu core number is a redundant part for the resource. And what's more, in some case, multiple executors may reside on one machine. Then it's not good to depend the node cpu core number for task assignment.

With multiple executors on one machine, this problem is indeed not solved. But for one machine and one executor, I understand that adding cpu cores will be more accurate.

**Comment by smallzhongfeng** [comment]
That's ok. I can understand now, and thank you very much for your answers, then I will close this issue first.
