### ISSUE TITLE
Why not include the `ballista-cli` in the member of workspace

### ISSUE THREAD

**Issue by liukun4515** [apache/arrow-ballista#88]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

 From https://github.com/apache/arrow-ballista/blob/a2c794e72f0b6e21b05bb8c05b38f68bba206a44/Cargo.toml#L27 toml file, the `ballista-cli` is exclude in the workspace.

Could you please explain this @andygrove ?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by andygrove** [comment]
I actually don't know why we chose to exclude DataFusion-cli and ballista-cli from the workspaces. It would seem better to me to include them.

**Comment by liukun4515** [comment]
> I actually don't know why we chose to exclude DataFusion-cli and ballista-cli from the workspaces. It would seem better to me to include them.

There is the context https://github.com/apache/arrow-datafusion/pull/2112 for removing the cli from the toml.
