### ISSUE TITLE
Failed to build docker image

### ISSUE THREAD

**Issue by monkeymq** [apache/arrow-ballista#912]
I'm following official document(https://arrow.apache.org/ballista/user-guide/deployment/docker.html）to deploy ballista using docker, but always encounter an error when executing step **_./dev/build-ballista-docker.sh_** which has troubled me for a day. I'm using CentOS 7.9, there are apart of logs below, can someone take a look?

```
Preparing to unpack .../nodejs_18.17.1-deb-1nodesource1_amd64.deb ...
Unpacking nodejs (18.17.1-deb-1nodesource1) ...
Setting up nodejs (18.17.1-deb-1nodesource1) ...

added 1 package in 999ms
npm notice
npm notice New major version of npm available! 9.6.7 -> 10.2.4
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.4>
npm notice Run `npm install -g npm@10.2.4` to update!
npm notice
Removing intermediate container 84d7ac058886
 ---> aa829093f723
Step 8/16 : RUN adduser -q -u $EXT_UID builder --home /home/builder &&     mkdir -p /home/builder/workspace
 ---> Running in 8092dd919670
adduser: The UID 0 is already in use.
The command '/bin/sh -c adduser -q -u $EXT_UID builder --home /home/builder &&     mkdir -p /home/builder/workspace' returned a non-zero code: 1

```

**Comment by zhangyuan** [comment]
I guess you are building the image with `root` or `sudo` to run. Use another with the permission to use `docker` command could resolve the issue. However the script assumes build with non-root user.

**Comment by monkeymq** [comment]
@zhangyuan Thank you for your suggestion that solved part of my problem, I say this because I also need to set permissions to some scripts before performing any steps (after git clone of course), i.e. `chmod a+rwx ./dev/docker/* .sh`, this works for me.

BTW, documentation for Ballista is a bit old and incorrect, which puts some people off.
