### ISSUE TITLE
Update dependencies in UI

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-ballista#957]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
There are a number of automated PRs to update UI dependencies:

- https://github.com/apache/arrow-ballista/pulls?q=is%3Aopen+is%3Apr+label%3Ajavascript

I have not merged any of these because we have no CI checks for the UI so we must update these dependencies manually.

**Describe the solution you'd like**
Update dependencies in UI

**Describe alternatives you've considered**

**Additional context**

**Comment by simicd** [comment]
Hi @andygrove, I'd like to pick up this task and update the UI dependencies

**Comment by simicd** [comment]
Hi @andygrove, thanks for merging the PR - I went through the dependabot PRs related to UI and these two can be closed:
- #893
- #922

I would have closed them myself but the command `@dependabot close` seems to only work with elevated access rights.

**Comment by andygrove** [comment]
Thanks @simicd I have closed those issues
